### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by debuluoyizhe** [Jianf-Wang/GBDL#2]

**Comment by debuluoyizhe** [comment]
Hello, could you please explain the division of the data set, or supplement,thanks.

**Comment by debuluoyizhe** [comment]
Hello, could you please explain the division of the data set, or supplement,thanks.
Since the number of png pages in each data set is different, I would like to know how the data set is divided.I had this problem
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/wb/Desktop/gbdl-dataset/dataset/KiTS19/kits19-slice/case_00106
/segmentation\\segmentation-22.png'

**Comment by Jianf-Wang** [comment]
Hi, thanks for your attention to this work. Did u change the dataset.py file by yourself ? I remember that the zero-padding operation is used when the number of slices is not enough for each case.

**Comment by debuluoyizhe** [comment]
> Hi, thanks for your attention to this work. Did u change the dataset.py file by yourself ? I remember that the zero-padding operation is used when the number of slices is not enough for each case.

Thank you very much for your reply. I solved this problem, but there is another problem. I want to know whether the training set and test set are randomly divided

**Comment by Jianf-Wang** [comment]
Yes, they are. Plus, there is another similar issue here https://github.com/Jianf-Wang/GBDL/issues/1
